# Generated by Django 5.1.15 on 2026-01-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('publish', 'Published'), ('email_required', 'Email Required')], default='email_required', max_length=20),
        ),
    ]
