# Generated by Django 5.1.15 on 2026-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('email_required', 'Email Required')], default='email_required', max_length=20),
        ),
    ]
