# Generated by Django 5.1.15 on 2026-01-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='Can students view this lesson without enrolling?'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('publish', 'Published'), ('draft', 'Draft'), ('soon', 'Coming Soon')], default='publish', max_length=10),
        ),
    ]
